### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by D0N2k** [a-tal/esi-knife#8]
I got the problem that as soon as I start the fetching process. The worker crashes with this error:

```Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/var/customers/webs/knife/esi_knife/worker.py", line 587, in knife
    results = get_results(public, character_id, scopes, roles, headers)
  File "/var/customers/webs/knife/esi_knife/worker.py", line 557, in get_results
    results = _get_all_data(scopes, roles, known_params, all_params, headers)
  File "/var/customers/webs/knife/esi_knife/worker.py", line 320, in _get_all_data
    headers,
  File "/var/customers/webs/knife/esi_knife/worker.py", line 213, in expand_params
    oper = spec["paths"][url]["get"]
KeyError: '/corporations/{corporation_id}/outposts/'
2018-07-30T10:50:16Z <Greenlet "Greenlet-0" at 0x7fec9d4d6998: knife('REMOVED :)', u'REMOVED, {u'Scopes': u'esi-alliances.read_contacts.v1 esi-a, {u'roles_at_other': [u'Hangar_Take_4', u'Hangar_Ta)> failed with KeyError

[2018-07-30 12:50:24 +0000] [9230] [WARNING] worker crashed: Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/var/customers/webs/knife/esi_knife/worker.py", line 587, in knife
    results = get_results(public, character_id, scopes, roles, headers)
  File "/var/customers/webs/knife/esi_knife/worker.py", line 557, in get_results
    results = _get_all_data(scopes, roles, known_params, all_params, headers)
  File "/var/customers/webs/knife/esi_knife/worker.py", line 320, in _get_all_data
    headers,
  File "/var/customers/webs/knife/esi_knife/worker.py", line 213, in expand_params
    oper = spec["paths"][url]["get"]
KeyError: '/corporations/{corporation_id}/outposts/'```

Thanks :)

**Comment by a-tal** [comment]
thanks for reporting this! should be fixed now
